apiVersion: apps/v1
kind: Deployment
metadata:
        name: jenkins-master
spec:
        selector:
          matchLabels:
            app: jenkins-master
        replicas: 1
        template:
          metadata:
            labels:
              app: jenkins-master
          spec:
            securityContext:
              fsGroup: 1000
              runAsUser: 0
            containers:
              - name: jenkins
                image: 232383674343.dkr.ecr.us-east-1.amazonaws.com/argojen:5
                env:
                  - name: JAVA_OPTS
                    value: -Djenkins.install.runSetupWizard=false
                ports:
                  - name: http-port
                    containerPort: 8080
                  - name: jnlp-port
                    containerPort: 50000
                volumeMounts:
                  - name: jenkins-home
                    mountPath: /var/jenkins_home
            volumes:
              - name: jenkins-home
                emptyDir: {}
